--Crear ENTIDAD PARA APP DE TIENDA

CREATE TABLE CLIENTE(

    ID_CLIENTE NUMBER,
    NOMBRE NVARCHAR2(100),
    APELLIDO NVARCHAR2(100),
    EDAD NUMBER,
    DIRECCION NVARCHAR2(100),
    ESTADO NVARCHAR2(100),
    TIENDA_ID NUMBER,
    CONSTRAINT CLIENTE_PK PRIMARY KEY(ID_CLIENTE)
);

INSERT INTO CLIENTE VALUES(1,'CARLOS','LOPEZ',25,'CALLE INDEPENDENCIA','TLAXCALA',7);

COMMIT;

SELECT * FROM CLIENTE;