CREATE TABLE TIENDA(
    ID_TIENDA NUMBER,
    NOMBRE NVARCHAR2(100),
    DIRECCION NVARCHAR2(100),
    ESTADO NVARCHAR2(100),
    INGRESO NUMBER,
    CONSTRAINT TIENDA_PK PRIMARY KEY(ID_TIENDA)
);

INSERT INTO TIENDA VALUES(1,'7LEVEN','CALLE 16 DE SEPTIEMBRE','CHIAPAS',130000);
COMMIT;

DELETE FROM TIENDA WHERE ID_TIENDA = 0;

SELECT * FROM TIENDA;

